#!/usr/bin/env bash

# This is intended for use as part of a Travis CI build, for projects
# that use Qless. Qless needs redis 2.6 (which has RC release but no
# final yet), and Travis has 2.4 installed. This will install and
# start 2.6 as a daemon.
#
# In your .travis.yml, add:
# before_install:
#  - curl -s https://raw.github.com/seomoz/qless-core/master/scripts/install_and_run_redis_2_6 | sh

# kill the script on error
set -e

# this is needed by redis
sudo apt-get install tcl8.5

REDIS_VERSION=2.6.0-rc6

# Check what is running
redis-cli info | grep redis_version

# shutdown the 2.4 server
redis-cli shutdown

# download
wget http://redis.googlecode.com/files/redis-$REDIS_VERSION.tar.gz

# extract
tar xzf redis-$REDIS_VERSION.tar.gz

# make
cd redis-$REDIS_VERSION
REDIS_26_DIR=`pwd`
make

# daemonize!
echo "daemonize yes" > redis.conf

# start the 2.6 server
cd $REDIS_26_DIR
./src/redis-server redis.conf

./src/redis-server -v
redis-server -v

# Verify that 2.6 is running
redis-cli info | grep redis_version

echo DONE
